/**import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ActivityIndicator, Alert, Image } from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { StreamVideo, StreamVideoClient, User, Call, CallContent } from '@stream-io/video-react-native-sdk';
import { Ionicons } from '@expo/vector-icons';
import { getDoc, doc } from 'firebase/firestore';
import { db } from '../../firebaseConfig';

// Define your Stream.io API key
const apiKey = 'YOUR_STREAM_API_KEY'; // Replace with your Stream API key

const VideoCallScreen = () => {
  const router = useRouter();
  const params = useLocalSearchParams();
  
  const chatId = typeof params.chatId === 'string' ? params.chatId : '';
  const receiverId = typeof params.receiverId === 'string' ? params.receiverId : '';
  const receiverName = typeof params.receiverName === 'string' ? params.receiverName : '';
  const currentUserId = typeof params.currentUserId === 'string' ? params.currentUserId : '';
  
  const [client, setClient] = useState<StreamVideoClient | null>(null);
  const [call, setCall] = useState<Call | null>(null);
  const [loading, setLoading] = useState(true);
  const [receiverToken, setReceiverToken] = useState<string | null>(null);
  const [callStatus, setCallStatus] = useState('connecting');
  
  // Generate a call ID based on the users involved
  const callId = chatId ? `call-${chatId}` : `call-${[currentUserId, receiverId].sort().join('-')}`;

  useEffect(() => {
    // Initialize Stream Video client with user info
    const initClient = async () => {
      if (!currentUserId) {
        Alert.alert('Error', 'User not authenticated');
        router.back();
        return;
      }
      
      try {
        // Fetch user data from Firebase (to get user's name)
        const userDoc = await getDoc(doc(db, 'users', currentUserId));
        const userData = userDoc.exists() ? userDoc.data() : null;
        const userName = userData?.name || 'User';
        
        // User object for Stream Video
        const user: User = {
          id: currentUserId,
          name: userName,
          image: userData?.avatar || undefined,
        };
        
        // This token would normally be generated by your backend
        // In a production app, don't generate tokens on the client side
        // For demo, we're using a dummy token (should be replaced)
        const token = 'dummy-token-replace-this';
        
        // Create and connect the Stream Video client
        const streamClient = new StreamVideoClient({
          apiKey,
          user,
          token,
        });
        
        await streamClient.connectUser();
        setClient(streamClient);
        
        // Initialize or join the call
        const callType = 'default';
        const callOptions = { ring: true };
        
        let activeCall;
        try {
          // Try to get the call if it exists
          activeCall = streamClient.call(callType, callId);
          await activeCall.getOrCreate(callOptions);
        } catch (error) {
          console.error('Error initializing call:', error);
          Alert.alert('Call Error', 'Could not establish call connection');
          router.back();
          return;
        }
        
        setCall(activeCall);
        
        // Listen for call state changes
        const unsubscribe = activeCall.on('call.updated', () => {
          const state = activeCall.state.call?.state;
          setCallStatus(state || 'unknown');
          
          if (state === 'ended') {
            Alert.alert('Call Ended', 'The call has ended');
            router.back();
          }
        });
        
        // Update receiver about incoming call (in a real app, this would be handled by push notifications)
        // For demo, we're just simulating this process
        await notifyReceiver();
        
        setLoading(false);
        
        return () => {
          unsubscribe();
          // Clean up the call when component unmounts
          if (activeCall) {
            activeCall.leave();
          }
          streamClient.disconnectUser();
        };
      } catch (error) {
        console.error('Error setting up video call:', error);
        Alert.alert('Setup Error', 'Could not set up video call');
        router.back();
      }
    };
    
    initClient();
  }, [currentUserId, receiverId, callId]);
  
  // Simulating notification to receiver (in a real app, you'd use push notifications)
  const notifyReceiver = async () => {
    // In a production app, you would:
    // 1. Call your backend API to trigger a push notification to the receiver
    // 2. The notification would prompt them to join the call
    // 3. Your backend would generate a proper token for the receiver
    
    console.log(`Notifying user ${receiverId} about incoming call ${callId}`);
    // Simulate receiving a token for demo purposes
    setReceiverToken('dummy-receiver-token');
  };
  
  const handleEndCall = async () => {
    if (!call) return;
    
    try {
      // End the call for all participants
      await call.leave();
      router.back();
    } catch (error) {
      console.error('Error ending call:', error);
    }
  };
  
  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#6549FE" />
        <Text style={styles.loadingText}>Setting up video call...</Text>
      </View>
    );
  }
  
  if (!client || !call) {
    return (
      <View style={styles.errorContainer}>
        <Text style={styles.errorText}>Could not initialize video call</Text>
        <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
          <Text style={styles.backButtonText}>Go Back</Text>
        </TouchableOpacity>
      </View>
    );
  }
  
  return (
    <StreamVideo client={client}>
      <View style={styles.container}>
        <View style={styles.headerBar}>
          <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
            <Ionicons name="arrow-back" size={24} color="#FFFFFF" />
          </TouchableOpacity>
          <Text style={styles.headerText}>
            {callStatus === 'ringing' 
              ? `Calling ${receiverName}...`
              : callStatus === 'connecting'
              ? 'Connecting...'
              : callStatus === 'joined'
              ? `In call with ${receiverName}`
              : 'Video Call'}
          </Text>
        </View>
        
        <CallContent call={call} />
        
        <View style={styles.controlsContainer}>
          <TouchableOpacity 
            style={styles.endCallButton} 
            onPress={handleEndCall}
          >
            <Ionicons name="call" size={28} color="#FFFFFF" />
          </TouchableOpacity>
          
          <TouchableOpacity 
            style={styles.toggleButton}
            onPress={() => call.camera.toggle()}
          >
            <Ionicons name="videocam" size={24} color="#FFFFFF" />
          </TouchableOpacity>
          
          <TouchableOpacity 
            style={styles.toggleButton}
            onPress={() => call.microphone.toggle()}
          >
            <Ionicons name="mic" size={24} color="#FFFFFF" />
          </TouchableOpacity>
          
          <TouchableOpacity 
            style={styles.toggleButton}
            onPress={() => call.speaker.toggle()}
          >
            <Ionicons name="volume-high" size={24} color="#FFFFFF" />
          </TouchableOpacity>
        </View>
      </View>
    </StreamVideo>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a1a',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
  },
  loadingText: {
    color: '#FFFFFF',
    marginTop: 16,
    fontSize: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    padding: 20,
  },
  errorText: {
    color: '#FFFFFF',
    fontSize: 18,
    marginBottom: 20,
    textAlign: 'center',
  },
  backButton: {
    backgroundColor: '#6549FE',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
  },
  backButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: 'rgba(0,0,0,0.6)',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  backBtn: {
    padding: 8,
  },
  headerText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 16,
  },
  controlsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: 'rgba(0,0,0,0.6)',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  endCallButton: {
    backgroundColor: '#FF3B30',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 8,
    transform: [{ rotate: '135deg' }],
  },
  toggleButton: {
    backgroundColor: '#6549FE',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 8,
  },
});

export default VideoCallScreen;*/